spring.application.name=reparo
spring.datasource.url=jdbc:postgresql://localhost:5432/reparo
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

app.jwt.secret=change-this-to-a-long-secret-key-at-least-32-chars
app.jwt.expiration-ms=86400000